name: webhook
version: 1
status: ACTIVE
resource_size: m
apiVersion: 3
save_progress: false
use_latest_snapshot: false
sources:
  base-sepolia.logs:
    dataset_name: base-sepolia.logs
    version: 1.0.0
    type: dataset
    description: Enriched logs for events emitted from contracts. Contains the
      contract address, data, topics, decoded event and metadata for blocks and
      transactions.
    display_name: Logs
transforms: {}
sinks:
  sink_1:
    url: https://webhook.site/d06324e8-d273-45b4-a18b-c4ad69c6e7e6
    type: webhook
    headers: {}
    description: Webhook sink from ethereum_sepolia.raw_logs
    from: base-sepolia.logs
    secret_name: WEBHOOK_SECRET_CM3UPDBJC0
